services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: gamingrealmdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gamingrealmdb"]
      interval: 2s
      timeout: 1s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gr-backend:
    container_name: gr-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GR_DATABASE_URL: postgres://admin:adminpw@postgres:5432/gamingrealmdb
    volumes:
      - .:/GR-backend

volumes:
  postgres_data:
