[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend for Gaming Realm - a project built for Avishkar 2022"
authors = ["Anand Krishna <anand2312@proton.me>", "Vivek Ashokkumar <vivekashok1221@gmail.com>", "Gautham Krishna Jayasurya <gautham.jayasurya@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "backend", from = "src"}]

[tool.poetry.dependencies]
python = "3.11.*"
fastapi = "^0.104.0"
prisma = "^0.9.1"
loguru = "^0.7.0"
uvicorn = {extras = ["fast"], version = "^0.23.1"}
python-multipart = "^0.0.6"
passlib = {extras = ["argon2"], version = "^1.7.4"}
pydantic = {extras = ["email"], version = "^1.10.2"}
storage3 = "^0.5.2"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
taskipy = "^1.10.3"
flake8 = "^5.0.4"
flake8-annotations = "^2.9.1"
flake8-bugbear = "^22.10.27"
flake8-docstrings = "^1.6.0"
pyright = "^1.1.279"
faker = "^15.3.1"
pytest = "^7.3.2"
asgi-lifespan = "^2.1.0"

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.taskipy.tasks]
lint = { cmd = "pre-commit run --all-files", help = "Lints project." }
format = { cmd = "black .", help = "Runs Black autoformatter." }
runserver = { cmd = "uvicorn --reload src.backend.app:app", help = "Runs the backend server." }
test = { cmd = "./scripts/migrate_and_test.sh", help = "Starts a test Postgres container, generates Prisma client, runs tests and then stops the container." }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
