name: Deploy to VPS

on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Watchtower on VPS
        env:
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $WATCHTOWER_TOKEN" https://watchtower.lnkshrt.xyz/v1/update
  trigger_frontend_action:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Trigger repository_dispatch event on gamingrealm-frontend
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/idkbrowby/gamingrealm-frontend/dispatches \
            -d '{"event_type":"on-backend-deploy", "client_payload": {}}'
