name: CI / CD

on: [pull_request, push, workflow_dispatch]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-and-deploy.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
